class SuraData{
  final String SuraNameAr;
  final String SuraNameEn;
  final int verses;

  SuraData({
    required this.SuraNameAr,
    required this.SuraNameEn,
    required this.verses,
  });

}
 
  List<SuraData> getSuras() {
    return suras;
  }

List<SuraData> suras = [
  SuraData(SuraNameAr: 'الفاتحة', SuraNameEn: 'Al-Fatiha', verses: 7),
  SuraData(SuraNameAr: 'البقرة', SuraNameEn: 'Al-Baqarah', verses: 286),
  SuraData(SuraNameAr: 'آل عمران', SuraNameEn: 'Aal-E-Imran', verses: 200),
  SuraData(SuraNameAr: 'النساء', SuraNameEn: 'An-Nisa', verses: 176),
  SuraData(SuraNameAr: 'المائدة', SuraNameEn: 'Al-Maida', verses: 120),
  SuraData(SuraNameAr: 'الأنعام', SuraNameEn: 'Al-Anam', verses: 165),
  SuraData(SuraNameAr: 'الأعراف', SuraNameEn: 'Al-Araf', verses: 206),
  SuraData(SuraNameAr: 'الأنفال', SuraNameEn: 'Al-Anfal', verses: 75),
  SuraData(SuraNameAr: 'التوبة', SuraNameEn: 'At-Tawba', verses: 129),
  SuraData(SuraNameAr: 'يونس', SuraNameEn: 'Yunus', verses: 109),
  SuraData(SuraNameAr: 'هود', SuraNameEn: 'Hud', verses: 123),
  SuraData(SuraNameAr: 'يوسف', SuraNameEn: 'Yusuf', verses: 111),
  SuraData(SuraNameAr: 'الرعد', SuraNameEn: 'Ar-Rad', verses: 43),
  SuraData(SuraNameAr: 'إبراهيم', SuraNameEn: 'Ibrahim', verses: 52),
  SuraData(SuraNameAr: 'الحجر', SuraNameEn: 'Al-Hijr', verses: 99),
  SuraData(SuraNameAr: 'النحل', SuraNameEn: 'An-Nahl', verses: 128),
  SuraData(SuraNameAr: 'الإسراء', SuraNameEn: 'Al-Isra', verses: 111),
  SuraData(SuraNameAr: 'الكهف', SuraNameEn: 'Al-Kahf', verses: 110),
  SuraData(SuraNameAr: 'مريم', SuraNameEn: 'Maryam', verses: 98),
  SuraData(SuraNameAr: 'طه', SuraNameEn: 'Taha', verses: 135),
  SuraData(SuraNameAr: 'الأنبياء', SuraNameEn: 'Al-Anbiya', verses: 112),
  SuraData(SuraNameAr: 'الحج', SuraNameEn: 'Al-Hajj', verses: 78),
  SuraData(SuraNameAr: 'المؤمنون', SuraNameEn: 'Al-Muminun', verses: 118),
  SuraData(SuraNameAr: 'النور', SuraNameEn: 'An-Nur', verses: 64),
  SuraData(SuraNameAr: 'الفرقان', SuraNameEn: 'Al-Furqan', verses: 77),
  SuraData(SuraNameAr: 'الشعراء', SuraNameEn: 'Ash-Shuara', verses: 227),
  SuraData(SuraNameAr: 'النمل', SuraNameEn: 'An-Naml', verses: 93),
  SuraData(SuraNameAr: 'القصص', SuraNameEn: 'Al-Qasas', verses: 88),
  SuraData(SuraNameAr: 'العنكبوت', SuraNameEn: 'Al-Ankabut', verses: 69),
  SuraData(SuraNameAr: 'الروم', SuraNameEn: 'Ar-Rum', verses: 60),
  SuraData(SuraNameAr: 'لقمان', SuraNameEn: 'Luqman', verses: 34),
  SuraData(SuraNameAr: 'السجدة', SuraNameEn: 'As-Sajda', verses: 30),
  SuraData(SuraNameAr: 'الأحزاب', SuraNameEn: 'Al-Ahzab', verses: 73),
  SuraData(SuraNameAr: 'سبأ', SuraNameEn: 'Saba', verses: 54),
  SuraData(SuraNameAr: 'فاطر', SuraNameEn: 'Fatir', verses: 45),
  SuraData(SuraNameAr: 'يس', SuraNameEn: 'Ya-Sin', verses: 83),
  SuraData(SuraNameAr: 'الصافات', SuraNameEn: 'As-Saffat', verses: 182),
  SuraData(SuraNameAr: 'ص', SuraNameEn: 'Sad', verses: 88),
  SuraData(SuraNameAr: 'الزمر', SuraNameEn: 'Az-Zumar', verses: 75),
  SuraData(SuraNameAr: 'غافر', SuraNameEn: 'Ghafir', verses: 85),
  SuraData(SuraNameAr: 'فصلت', SuraNameEn: 'Fussilat', verses: 54),
  SuraData(SuraNameAr: 'الشورى', SuraNameEn: 'Ash-Shura', verses: 53),
  SuraData(SuraNameAr: 'الزخرف', SuraNameEn: 'Az-Zukhruf', verses: 89),
  SuraData(SuraNameAr: 'الدخان', SuraNameEn: 'Ad-Dukhan', verses: 59),
  SuraData(SuraNameAr: 'الجاثية', SuraNameEn: 'Al-Jathiya', verses: 37),
  SuraData(SuraNameAr: 'الأحقاف', SuraNameEn: 'Al-Ahqaf', verses: 35),
  SuraData(SuraNameAr: 'محمد', SuraNameEn: 'Muhammad', verses: 38),
  SuraData(SuraNameAr: 'الفتح', SuraNameEn: 'Al-Fath', verses: 29),
  SuraData(SuraNameAr: 'الحجرات', SuraNameEn: 'Al-Hujurat', verses: 18),
  SuraData(SuraNameAr: 'ق', SuraNameEn: 'Qaf', verses: 45),
  SuraData(SuraNameAr: 'الذاريات', SuraNameEn: 'Adh-Dhariyat', verses: 60),
  SuraData(SuraNameAr: 'الطور', SuraNameEn: 'At-Tur', verses: 49),
  SuraData(SuraNameAr: 'النجم', SuraNameEn: 'An-Najm', verses: 62),
  SuraData(SuraNameAr: 'القمر', SuraNameEn: 'Al-Qamar', verses: 55),
  SuraData(SuraNameAr: 'الرحمن', SuraNameEn: 'Ar-Rahman', verses: 78),
  SuraData(SuraNameAr: 'الواقعة', SuraNameEn: 'Al-Waqia', verses: 96),
  SuraData(SuraNameAr: 'الحديد', SuraNameEn: 'Al-Hadid', verses: 29),
  SuraData(SuraNameAr: 'المجادلة', SuraNameEn: 'Al-Mujadila', verses: 22),
  SuraData(SuraNameAr: 'الحشر', SuraNameEn: 'Al-Hashr', verses: 24),
  SuraData(SuraNameAr: 'الممتحنة', SuraNameEn: 'Al-Mumtahina', verses: 13),
  SuraData(SuraNameAr: 'الصف', SuraNameEn: 'As-Saff', verses: 14),
  SuraData(SuraNameAr: 'الجمعة', SuraNameEn: 'Al-Jumua', verses: 11),
  SuraData(SuraNameAr: 'المنافقون', SuraNameEn: 'Al-Munafiqun', verses: 11),
  SuraData(SuraNameAr: 'التغابن', SuraNameEn: 'At-Taghabun', verses: 18),
  SuraData(SuraNameAr: 'الطلاق', SuraNameEn: 'At-Talaq', verses: 12),
  SuraData(SuraNameAr: 'التحريم', SuraNameEn: 'At-Tahrim', verses: 12),
  SuraData(SuraNameAr: 'الملك', SuraNameEn: 'Al-Mulk', verses: 30),
  SuraData(SuraNameAr: 'القلم', SuraNameEn: 'Al-Qalam', verses: 52),
  SuraData(SuraNameAr: 'الحاقة', SuraNameEn: 'Al-Haqqa', verses: 52),
  SuraData(SuraNameAr: 'المعارج', SuraNameEn: 'Al-Maarij', verses: 44),
  SuraData(SuraNameAr: 'نوح', SuraNameEn: 'Nuh', verses: 28),
  SuraData(SuraNameAr: 'الجن', SuraNameEn: 'Al-Jinn', verses: 28),
  SuraData(SuraNameAr: 'المزمل', SuraNameEn: 'Al-Muzzammil', verses: 20),
  SuraData(SuraNameAr: 'المدثر', SuraNameEn: 'Al-Muddathir', verses: 56),
  SuraData(SuraNameAr: 'القيامة', SuraNameEn: 'Al-Qiyama', verses: 40),
  SuraData(SuraNameAr: 'الانسان', SuraNameEn: 'Al-Insan', verses: 31),
  SuraData(SuraNameAr: 'المرسلات', SuraNameEn: 'Al-Mursalat', verses: 50),
  SuraData(SuraNameAr: 'النبأ', SuraNameEn: 'An-Naba', verses: 40),
  SuraData(SuraNameAr: 'النازعات', SuraNameEn: 'An-Naziat', verses: 46),
  SuraData(SuraNameAr: 'عبس', SuraNameEn: 'Abasa', verses: 42),
  SuraData(SuraNameAr: 'التكوير', SuraNameEn: 'At-Takwir', verses: 29),
  SuraData(SuraNameAr: 'الانفطار', SuraNameEn: 'Al-Infitar', verses: 19),
  SuraData(SuraNameAr: 'المطففين', SuraNameEn: 'Al-Mutaffifin', verses: 36),
  SuraData(SuraNameAr: 'الانشقاق', SuraNameEn: 'Al-Inshiqaq', verses: 25),
  SuraData(SuraNameAr: 'البروج', SuraNameEn: 'Al-Buruj', verses: 22),
  SuraData(SuraNameAr: 'الطارق', SuraNameEn: 'At-Tariq', verses: 17),
  SuraData(SuraNameAr: 'الأعلى', SuraNameEn: 'Al-Ala', verses: 19),
  SuraData(SuraNameAr: 'الغاشية', SuraNameEn: 'Al-Ghashiya', verses: 26),
  SuraData(SuraNameAr: 'الفجر', SuraNameEn: 'Al-Fajr', verses: 30),
  SuraData(SuraNameAr: 'البلد', SuraNameEn: 'Al-Balad', verses: 20),
  SuraData(SuraNameAr: 'الشمس', SuraNameEn: 'Ash-Shams', verses: 15),
  SuraData(SuraNameAr: 'الليل', SuraNameEn: 'Al-Lail', verses: 21),
  SuraData(SuraNameAr: 'الضحى', SuraNameEn: 'Ad-Duha', verses: 11),
  SuraData(SuraNameAr: 'الشرح', SuraNameEn: 'Ash-Sharh', verses: 8),
  SuraData(SuraNameAr: 'التين', SuraNameEn: 'At-Tin', verses: 8),
  SuraData(SuraNameAr: 'العلق', SuraNameEn: 'Al-Alaq', verses: 19),
  SuraData(SuraNameAr: 'القدر', SuraNameEn: 'Al-Qadr', verses: 5),
  SuraData(SuraNameAr: 'البينة', SuraNameEn: 'Al-Bayyina', verses: 8),
  SuraData(SuraNameAr: 'الزلزلة', SuraNameEn: 'Az-Zalzalah', verses: 8),
  SuraData(SuraNameAr: 'العاديات', SuraNameEn: 'Al-Adiyat', verses: 11),
  SuraData(SuraNameAr: 'القارعة', SuraNameEn: 'Al-Qaria', verses: 11),
  SuraData(SuraNameAr: 'التكاثر', SuraNameEn: 'At-Takathur', verses: 8),
  SuraData(SuraNameAr: 'العصر', SuraNameEn: 'Al-Asr', verses: 3),
  SuraData(SuraNameAr: 'الهمزة', SuraNameEn: 'Al-Humazah', verses: 9),
  SuraData(SuraNameAr: 'الفيل', SuraNameEn: 'Al-Fil', verses: 5),
  SuraData(SuraNameAr: 'قريش', SuraNameEn: 'Quraish', verses: 4),
  SuraData(SuraNameAr: 'الماعون', SuraNameEn: 'Al-Maun', verses: 7),
  SuraData(SuraNameAr: 'الكوثر', SuraNameEn: 'Al-Kawthar', verses: 3),
  SuraData(SuraNameAr: 'الكافرون', SuraNameEn: 'Al-Kafiroon', verses: 6),
  SuraData(SuraNameAr: 'النصر', SuraNameEn: 'An-Nasr', verses: 3),
  SuraData(SuraNameAr: 'المسد', SuraNameEn: 'Al-Masad', verses: 5),
  SuraData(SuraNameAr: 'الإخلاص', SuraNameEn: 'Al-Ikhlas', verses: 4),
  SuraData(SuraNameAr: 'الفلق', SuraNameEn: 'Al-Falaq', verses: 5),
  SuraData(SuraNameAr: 'الناس', SuraNameEn: 'An-Nas', verses: 6),
];